version: "3"

env:
  PROJECT_NAME: threefive

dotenv: [".env"]

tasks:
  default:
    desc: Show all available tasks
    cmds:
      - task --list

  tidy:
    desc: Install Go Dependencies
    cmds:
      - go mod tidy

  build:
    desc: Build Go binary only
    deps: [templ, tailwind]
    cmds:
      - go build -o ./tmp/main ./cmd/api

    # 🧩 Templ
  templ:
    desc: Compile .templ files into Go code
    cmds:
      - templ generate

  # 🎨 TailwindCSS
  tailwind:
    desc: Generate CSS from Tailwind input file
    cmds:
      - npx tailwindcss -i ./ui/static/css/input.css -o ./ui/static/css/tailwind.css --minify

  test:
    desc: Run Go tests
    cmds:
      - go test ./...

  # 🐤 Goose migrations
  db:create:
    desc: Create a new goose migration
    cmds:
      - goose create {{.CLI_ARGS}} sql
    dir: ./db/migrations

  db:up:
    desc: Apply all up migrations
    cmds:
      - goose -dir ./db/migrations/ up

  db:down:
    desc: Roll back the last migration
    cmds:
      - goose -dir ./db/migrations/ down

  db:status:
    desc: Show current migration status
    cmds:
      - goose status
    dir: ./db/migrations

  # 🧬 SQLC code generation
  db:generate:
    desc: Generate Go code from SQL files
    cmds:
      - sqlc generate

  docker:up:
    desc: Start QL container
    cmds:
      - docker-compose up -d

  docker:down:
    desc: Stop all Docker containers
    cmds:
      - docker-compose down

  docker:logs:
    desc: View database logs
    cmds:
      - docker-compose logs -f

  docker:psql:
    desc: Open psql shell to the DB container
    cmds:
      - docker exec -it  psql -U user -d sabiflow
