// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package auth

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	Token  string             `db:"token"`
	Data   []byte             `db:"data"`
	Expiry pgtype.Timestamptz `db:"expiry"`
}

type User struct {
	ID           int32              `db:"id"`
	FirstName    string             `db:"first_name"`
	LastName     string             `db:"last_name"`
	Email        string             `db:"email"`
	PasswordHash string             `db:"password_hash"`
	CreatedAt    pgtype.Timestamptz `db:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at"`
}
