// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           int32            `db:"id"`
	FirstName    string           `db:"first_name"`
	LastName     string           `db:"last_name"`
	Email        string           `db:"email"`
	PasswordHash string           `db:"password_hash"`
	CreatedAt    pgtype.Timestamp `db:"created_at"`
	UpdatedAt    pgtype.Timestamp `db:"updated_at"`
}
