// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks_feature.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createFeatureBlock = `-- name: CreateFeatureBlock :one


INSERT INTO block_feature (
  block_id, 
  title,
  description,
  heading,
  subheading
)
VALUES (
  $1, 
  $2,
  $3,
  $4,
  $5
)
RETURNING id, block_id, title, description, heading, subheading
`

type CreateFeatureBlockParams struct {
	BlockID     uuid.UUID `json:"block_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Heading     string    `json:"heading"`
	Subheading  string    `json:"subheading"`
}

// backend/sql/queries/blocks_feature.sql
// ============================================
// Feature Block Queries
// ============================================
func (q *Queries) CreateFeatureBlock(ctx context.Context, arg CreateFeatureBlockParams) (BlockFeature, error) {
	row := q.db.QueryRow(ctx, createFeatureBlock,
		arg.BlockID,
		arg.Title,
		arg.Description,
		arg.Heading,
		arg.Subheading,
	)
	var i BlockFeature
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Title,
		&i.Description,
		&i.Heading,
		&i.Subheading,
	)
	return i, err
}

const deleteFeatureBlock = `-- name: DeleteFeatureBlock :exec
DELETE FROM block_feature WHERE block_id = $1
`

func (q *Queries) DeleteFeatureBlock(ctx context.Context, blockID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteFeatureBlock, blockID)
	return err
}

const getFeatureBlockByBlockID = `-- name: GetFeatureBlockByBlockID :one
SELECT id, block_id, title, description, heading, subheading FROM block_feature
WHERE block_id = $1
`

func (q *Queries) GetFeatureBlockByBlockID(ctx context.Context, blockID uuid.UUID) (BlockFeature, error) {
	row := q.db.QueryRow(ctx, getFeatureBlockByBlockID, blockID)
	var i BlockFeature
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Title,
		&i.Description,
		&i.Heading,
		&i.Subheading,
	)
	return i, err
}

const getFeatureBlocksByEntity = `-- name: GetFeatureBlocksByEntity :many
SELECT bf.id, bf.block_id, bf.title, bf.description, bf.heading, bf.subheading
FROM block_feature bf
INNER JOIN blocks b ON b.id = bf.block_id
WHERE b.entity_type = $1 AND b.entity_id = $2
ORDER BY b.sort_order
`

type GetFeatureBlocksByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetFeatureBlocksByEntity(ctx context.Context, arg GetFeatureBlocksByEntityParams) ([]BlockFeature, error) {
	rows, err := q.db.Query(ctx, getFeatureBlocksByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockFeature
	for rows.Next() {
		var i BlockFeature
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.Title,
			&i.Description,
			&i.Heading,
			&i.Subheading,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFeatureBlock = `-- name: UpdateFeatureBlock :one
UPDATE block_feature
SET 
  title = COALESCE($1, title),
  description = COALESCE($2, description),
  heading = COALESCE($3, heading),
  subheading = COALESCE($4, subheading)
WHERE block_id = $5
RETURNING id, block_id, title, description, heading, subheading
`

type UpdateFeatureBlockParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Heading     string    `json:"heading"`
	Subheading  string    `json:"subheading"`
	BlockID     uuid.UUID `json:"block_id"`
}

func (q *Queries) UpdateFeatureBlock(ctx context.Context, arg UpdateFeatureBlockParams) (BlockFeature, error) {
	row := q.db.QueryRow(ctx, updateFeatureBlock,
		arg.Title,
		arg.Description,
		arg.Heading,
		arg.Subheading,
		arg.BlockID,
	)
	var i BlockFeature
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Title,
		&i.Description,
		&i.Heading,
		&i.Subheading,
	)
	return i, err
}
