// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blocks_about.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAboutBlock = `-- name: CreateAboutBlock :one


INSERT INTO block_about (
  block_id, 
  title,
  description,
  heading,
  subheading
)
VALUES (
  $1, 
  $2,
  $3,
  $4,
  $5
)
returning id, block_id, title, description, heading, subheading
`

type CreateAboutBlockParams struct {
	BlockID     uuid.UUID `json:"block_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Heading     string    `json:"heading"`
	Subheading  string    `json:"subheading"`
}

// backend/sql/queries/blocks_about.sql
// ============================================
// About Block Queries
// ============================================
func (q *Queries) CreateAboutBlock(ctx context.Context, arg CreateAboutBlockParams) (BlockAbout, error) {
	row := q.db.QueryRow(ctx, createAboutBlock,
		arg.BlockID,
		arg.Title,
		arg.Description,
		arg.Heading,
		arg.Subheading,
	)
	var i BlockAbout
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Title,
		&i.Description,
		&i.Heading,
		&i.Subheading,
	)
	return i, err
}

const deleteAboutBlock = `-- name: DeleteAboutBlock :exec
DELETE FROM block_about WHERE block_id = $1
`

func (q *Queries) DeleteAboutBlock(ctx context.Context, blockID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAboutBlock, blockID)
	return err
}

const getAboutBlockByBlockID = `-- name: GetAboutBlockByBlockID :one
SELECT id, block_id, title, description, heading, subheading FROM block_about
WHERE block_id = $1
`

func (q *Queries) GetAboutBlockByBlockID(ctx context.Context, blockID uuid.UUID) (BlockAbout, error) {
	row := q.db.QueryRow(ctx, getAboutBlockByBlockID, blockID)
	var i BlockAbout
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Title,
		&i.Description,
		&i.Heading,
		&i.Subheading,
	)
	return i, err
}

const getAboutBlocksByEntity = `-- name: GetAboutBlocksByEntity :many
SELECT ba.id, ba.block_id, ba.title, ba.description, ba.heading, ba.subheading
FROM block_about ba
INNER JOIN blocks b ON b.id = ba.block_id
WHERE b.entity_type = $1 AND b.entity_id = $2
ORDER BY b.sort_order
`

type GetAboutBlocksByEntityParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetAboutBlocksByEntity(ctx context.Context, arg GetAboutBlocksByEntityParams) ([]BlockAbout, error) {
	rows, err := q.db.Query(ctx, getAboutBlocksByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlockAbout
	for rows.Next() {
		var i BlockAbout
		if err := rows.Scan(
			&i.ID,
			&i.BlockID,
			&i.Title,
			&i.Description,
			&i.Heading,
			&i.Subheading,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAboutBlock = `-- name: UpdateAboutBlock :one
UPDATE block_about
SET 
  title = COALESCE($1, title),
  description = COALESCE($2, description),
  heading =  COALESCE($3, heading),
  subheading = COALESCE($4, subheading)
WHERE block_id = $5
RETURNING id, block_id, title, description, heading, subheading
`

type UpdateAboutBlockParams struct {
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Heading     string    `json:"heading"`
	Subheading  string    `json:"subheading"`
	BlockID     uuid.UUID `json:"block_id"`
}

func (q *Queries) UpdateAboutBlock(ctx context.Context, arg UpdateAboutBlockParams) (BlockAbout, error) {
	row := q.db.QueryRow(ctx, updateAboutBlock,
		arg.Title,
		arg.Description,
		arg.Heading,
		arg.Subheading,
		arg.BlockID,
	)
	var i BlockAbout
	err := row.Scan(
		&i.ID,
		&i.BlockID,
		&i.Title,
		&i.Description,
		&i.Heading,
		&i.Subheading,
	)
	return i, err
}
