// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: blogs.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkBlogSlugExists = `-- name: CheckBlogSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM blogs 
    WHERE slug = $1 
    AND deleted_at IS NULL
    AND ($2::uuid IS NULL OR id != $2)
)
`

type CheckBlogSlugExistsParams struct {
	Slug      string    `json:"slug"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

func (q *Queries) CheckBlogSlugExists(ctx context.Context, arg CheckBlogSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBlogSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countBlogs = `-- name: CountBlogs :one
SELECT COUNT(*) FROM blogs
WHERE deleted_at IS NULL
  AND ($1::text = '' OR status = $1::page_status)
  AND ($2::text = '' OR 
       ($2 = 'true' AND is_featured = true) OR 
       ($2 = 'false' AND is_featured = false))
`

type CountBlogsParams struct {
	Status     string `json:"status"`
	IsFeatured string `json:"is_featured"`
}

func (q *Queries) CountBlogs(ctx context.Context, arg CountBlogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBlogs, arg.Status, arg.IsFeatured)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPublishedBlogs = `-- name: CountPublishedBlogs :one
SELECT COUNT(*) FROM blogs
WHERE deleted_at IS NULL
  AND status = 'published'
  AND ($1::text = '' OR 
       ($1 = 'true' AND is_featured = true) OR 
       ($1 = 'false' AND is_featured = false))
`

func (q *Queries) CountPublishedBlogs(ctx context.Context, isFeatured string) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedBlogs, isFeatured)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBlog = `-- name: CreateBlog :one


INSERT INTO blogs (
    title,
    slug,
    status,
    description,
    reading_time,
    is_featured,
    featured_image_id,
    published_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type CreateBlogParams struct {
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Status          NullPageStatus     `json:"status"`
	Description     pgtype.Text        `json:"description"`
	ReadingTime     pgtype.Int4        `json:"reading_time"`
	IsFeatured      pgtype.Bool        `json:"is_featured"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

// backend/sql/queries/blogs.sql
// ============================================
// Blogs Queries
// ============================================
func (q *Queries) CreateBlog(ctx context.Context, arg CreateBlogParams) (Blogs, error) {
	row := q.db.QueryRow(ctx, createBlog,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Description,
		arg.ReadingTime,
		arg.IsFeatured,
		arg.FeaturedImageID,
		arg.PublishedAt,
	)
	var i Blogs
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Description,
		&i.ReadingTime,
		&i.IsFeatured,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlogByID = `-- name: GetBlogByID :one
SELECT id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at FROM blogs
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBlogByID(ctx context.Context, id uuid.UUID) (Blogs, error) {
	row := q.db.QueryRow(ctx, getBlogByID, id)
	var i Blogs
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Description,
		&i.ReadingTime,
		&i.IsFeatured,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBlogBySlug = `-- name: GetBlogBySlug :one
SELECT id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at FROM blogs
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBlogBySlug(ctx context.Context, slug string) (Blogs, error) {
	row := q.db.QueryRow(ctx, getBlogBySlug, slug)
	var i Blogs
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Description,
		&i.ReadingTime,
		&i.IsFeatured,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBlogs = `-- name: ListBlogs :many
SELECT id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at FROM blogs
WHERE deleted_at IS NULL
  AND ($1::text = '' OR status = $1::page_status)
  AND ($2::text = '' OR 
       ($2 = 'true' AND is_featured = true) OR 
       ($2 = 'false' AND is_featured = false))
ORDER BY 
  CASE WHEN $3 = 'created_at' AND $4 = 'desc' THEN created_at END DESC,
  CASE WHEN $3 = 'created_at' AND $4 = 'asc' THEN created_at END ASC,
  CASE WHEN $3 = 'published_at' AND $4 = 'desc' THEN published_at END DESC,
  CASE WHEN $3 = 'published_at' AND $4 = 'asc' THEN published_at END ASC,
  CASE WHEN $3 = 'title' AND $4 = 'desc' THEN title END DESC,
  CASE WHEN $3 = 'title' AND $4 = 'asc' THEN title END ASC,
  created_at DESC
LIMIT $6 OFFSET $5
`

type ListBlogsParams struct {
	Status     string      `json:"status"`
	IsFeatured string      `json:"is_featured"`
	SortBy     interface{} `json:"sort_by"`
	SortOrder  interface{} `json:"sort_order"`
	OffsetVal  int32       `json:"offset_val"`
	LimitVal   int32       `json:"limit_val"`
}

func (q *Queries) ListBlogs(ctx context.Context, arg ListBlogsParams) ([]Blogs, error) {
	rows, err := q.db.Query(ctx, listBlogs,
		arg.Status,
		arg.IsFeatured,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blogs
	for rows.Next() {
		var i Blogs
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.Description,
			&i.ReadingTime,
			&i.IsFeatured,
			&i.FeaturedImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedBlogs = `-- name: ListPublishedBlogs :many
SELECT id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at FROM blogs
WHERE deleted_at IS NULL
  AND status = 'published'
ORDER BY 
  CASE WHEN $1 = 'created_at' AND $2 = 'desc' THEN created_at END DESC,
  CASE WHEN $1 = 'created_at' AND $2 = 'asc' THEN created_at END ASC,
  CASE WHEN $1 = 'published_at' AND $2 = 'desc' THEN published_at END DESC,
  CASE WHEN $1 = 'published_at' AND $2 = 'asc' THEN published_at END ASC,
  CASE WHEN $1 = 'title' AND $2 = 'desc' THEN title END DESC,
  CASE WHEN $1 = 'title' AND $2 = 'asc' THEN title END ASC,
  published_at DESC
LIMIT $4 OFFSET $3
`

type ListPublishedBlogsParams struct {
	SortBy    interface{} `json:"sort_by"`
	SortOrder interface{} `json:"sort_order"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListPublishedBlogs(ctx context.Context, arg ListPublishedBlogsParams) ([]Blogs, error) {
	rows, err := q.db.Query(ctx, listPublishedBlogs,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blogs
	for rows.Next() {
		var i Blogs
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.Description,
			&i.ReadingTime,
			&i.IsFeatured,
			&i.FeaturedImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBlog = `-- name: SoftDeleteBlog :exec
UPDATE blogs
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteBlog(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteBlog, id)
	return err
}

const updateBlog = `-- name: UpdateBlog :one
UPDATE blogs
SET 
    title = COALESCE($1, title),
    slug = COALESCE($2, slug),
    status = COALESCE($3, status),
    description = $4,
    reading_time = $5,
    is_featured = COALESCE($6, is_featured),
    featured_image_id = $7,
    published_at = $8,
    updated_at = NOW()
WHERE id = $9
RETURNING id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type UpdateBlogParams struct {
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Status          NullPageStatus     `json:"status"`
	Description     pgtype.Text        `json:"description"`
	ReadingTime     pgtype.Int4        `json:"reading_time"`
	IsFeatured      pgtype.Bool        `json:"is_featured"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateBlog(ctx context.Context, arg UpdateBlogParams) (Blogs, error) {
	row := q.db.QueryRow(ctx, updateBlog,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.Description,
		arg.ReadingTime,
		arg.IsFeatured,
		arg.FeaturedImageID,
		arg.PublishedAt,
		arg.ID,
	)
	var i Blogs
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Description,
		&i.ReadingTime,
		&i.IsFeatured,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateBlogStatus = `-- name: UpdateBlogStatus :one
UPDATE blogs
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, title, slug, status, description, reading_time, is_featured, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type UpdateBlogStatusParams struct {
	Status NullPageStatus `json:"status"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateBlogStatus(ctx context.Context, arg UpdateBlogStatusParams) (Blogs, error) {
	row := q.db.QueryRow(ctx, updateBlogStatus, arg.Status, arg.ID)
	var i Blogs
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.Description,
		&i.ReadingTime,
		&i.IsFeatured,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}
