// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkSlugExists = `-- name: CheckSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM pages 
    WHERE slug = $1 
    AND deleted_at IS NULL
    AND ($2::uuid IS NULL OR id != $2)
)
`

type CheckSlugExistsParams struct {
	Slug      string    `json:"slug"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

func (q *Queries) CheckSlugExists(ctx context.Context, arg CheckSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countPages = `-- name: CountPages :one
SELECT COUNT(*) FROM pages
WHERE deleted_at IS NULL
  AND ($1::text = '' OR status = $1::page_status)
`

func (q *Queries) CountPages(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countPages, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one


INSERT INTO pages (
    title,
    slug,
    status,
    featured_image_id,
    published_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, title, slug, status, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type CreatePageParams struct {
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Status          NullPageStatus     `json:"status"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

// backend/sql/queries/pages.sql
// ============================================
// Pages Queries (Generic pages only)
// ============================================
func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (Pages, error) {
	row := q.db.QueryRow(ctx, createPage,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.FeaturedImageID,
		arg.PublishedAt,
	)
	var i Pages
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageByID = `-- name: GetPageByID :one
SELECT id, title, slug, status, featured_image_id, created_at, updated_at, published_at, deleted_at FROM pages
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPageByID(ctx context.Context, id uuid.UUID) (Pages, error) {
	row := q.db.QueryRow(ctx, getPageByID, id)
	var i Pages
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageBySlug = `-- name: GetPageBySlug :one
SELECT id, title, slug, status, featured_image_id, created_at, updated_at, published_at, deleted_at FROM pages
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPageBySlug(ctx context.Context, slug string) (Pages, error) {
	row := q.db.QueryRow(ctx, getPageBySlug, slug)
	var i Pages
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPages = `-- name: ListPages :many
SELECT id, title, slug, status, featured_image_id, created_at, updated_at, published_at, deleted_at FROM pages
WHERE deleted_at IS NULL
  AND ($1::text = '' OR status = $1::page_status)
ORDER BY 
  CASE WHEN $2 = 'created_at_desc' AND $3 = 'desc' THEN created_at END DESC,
  CASE WHEN $2 = 'created_at_asc' AND $3 = 'asc' THEN created_at END ASC,
  CASE WHEN $2 = 'published_at_desc' AND  $3 = 'desc' THEN published_at END DESC,
  CASE WHEN $2 = 'published_at_asc' AND $3 = 'asc' THEN published_at END ASC,
  created_at DESC
LIMIT $5 OFFSET $4
`

type ListPagesParams struct {
	Status    string      `json:"status"`
	SortBy    interface{} `json:"sort_by"`
	SortOrder interface{} `json:"sort_order"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListPages(ctx context.Context, arg ListPagesParams) ([]Pages, error) {
	rows, err := q.db.Query(ctx, listPages,
		arg.Status,
		arg.SortBy,
		arg.SortOrder,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Pages
	for rows.Next() {
		var i Pages
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Status,
			&i.FeaturedImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldDeletedPages = `-- name: PurgeOldDeletedPages :one
WITH deleted AS (
    DELETE FROM pages 
    WHERE deleted_at IS NOT NULL           -- Has been soft-deleted
      AND deleted_at < $1        -- @cutoff_date is a PARAMETER (not a column)
    RETURNING id
)
SELECT COUNT(*) as count FROM deleted
`

func (q *Queries) PurgeOldDeletedPages(ctx context.Context, cutoffDate pgtype.Timestamptz) (int64, error) {
	row := q.db.QueryRow(ctx, purgeOldDeletedPages, cutoffDate)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeletePage = `-- name: SoftDeletePage :exec
UPDATE pages
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeletePage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeletePage, id)
	return err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET 
    title = COALESCE($1, title),
    slug = COALESCE($2, slug),
    status = COALESCE($3, status),
    featured_image_id = $4,
    published_at = $5,
    updated_at = NOW()
WHERE id = $6
RETURNING id, title, slug, status, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type UpdatePageParams struct {
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Status          NullPageStatus     `json:"status"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (Pages, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.Title,
		arg.Slug,
		arg.Status,
		arg.FeaturedImageID,
		arg.PublishedAt,
		arg.ID,
	)
	var i Pages
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePageStatus = `-- name: UpdatePageStatus :one
UPDATE pages
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, title, slug, status, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type UpdatePageStatusParams struct {
	Status NullPageStatus `json:"status"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdatePageStatus(ctx context.Context, arg UpdatePageStatusParams) (Pages, error) {
	row := q.db.QueryRow(ctx, updatePageStatus, arg.Status, arg.ID)
	var i Pages
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Status,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}
