// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkProjectSlugExists = `-- name: CheckProjectSlugExists :one
SELECT EXISTS(
    SELECT 1 FROM projects 
    WHERE slug = $1 
    AND deleted_at IS NULL
    AND ($2::uuid IS NULL OR id != $2)
)
`

type CheckProjectSlugExistsParams struct {
	Slug      string    `json:"slug"`
	ExcludeID uuid.UUID `json:"exclude_id"`
}

func (q *Queries) CheckProjectSlugExists(ctx context.Context, arg CheckProjectSlugExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkProjectSlugExists, arg.Slug, arg.ExcludeID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*) FROM projects
WHERE deleted_at IS NULL
  AND ($1::page_status IS NULL OR status = $1)
`

func (q *Queries) CountProjects(ctx context.Context, status PageStatus) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one


INSERT INTO projects (
    title,
    slug,
    description,
    project_date,
    status,
    client_name,
    project_year,
    project_url,
    technologies,
    project_status,
    featured_image_id,
    published_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
RETURNING id, title, slug, description, project_date, status, client_name, project_year, project_url, technologies, project_status, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type CreateProjectParams struct {
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Description     pgtype.Text        `json:"description"`
	ProjectDate     pgtype.Date        `json:"project_date"`
	Status          NullPageStatus     `json:"status"`
	ClientName      pgtype.Text        `json:"client_name"`
	ProjectYear     pgtype.Int4        `json:"project_year"`
	ProjectUrl      pgtype.Text        `json:"project_url"`
	Technologies    []byte             `json:"technologies"`
	ProjectStatus   NullProjectStatus  `json:"project_status"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
}

// backend/sql/queries/projects.sql
// ============================================
// Projects Queries
// ============================================
func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Projects, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ProjectDate,
		arg.Status,
		arg.ClientName,
		arg.ProjectYear,
		arg.ProjectUrl,
		arg.Technologies,
		arg.ProjectStatus,
		arg.FeaturedImageID,
		arg.PublishedAt,
	)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ProjectDate,
		&i.Status,
		&i.ClientName,
		&i.ProjectYear,
		&i.ProjectUrl,
		&i.Technologies,
		&i.ProjectStatus,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, title, slug, description, project_date, status, client_name, project_year, project_url, technologies, project_status, featured_image_id, created_at, updated_at, published_at, deleted_at FROM projects
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectByID(ctx context.Context, id uuid.UUID) (Projects, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ProjectDate,
		&i.Status,
		&i.ClientName,
		&i.ProjectYear,
		&i.ProjectUrl,
		&i.Technologies,
		&i.ProjectStatus,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectBySlug = `-- name: GetProjectBySlug :one
SELECT id, title, slug, description, project_date, status, client_name, project_year, project_url, technologies, project_status, featured_image_id, created_at, updated_at, published_at, deleted_at FROM projects
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetProjectBySlug(ctx context.Context, slug string) (Projects, error) {
	row := q.db.QueryRow(ctx, getProjectBySlug, slug)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ProjectDate,
		&i.Status,
		&i.ClientName,
		&i.ProjectYear,
		&i.ProjectUrl,
		&i.Technologies,
		&i.ProjectStatus,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, title, slug, description, project_date, status, client_name, project_year, project_url, technologies, project_status, featured_image_id, created_at, updated_at, published_at, deleted_at FROM projects
WHERE deleted_at IS NULL
  AND ($1::page_status IS NULL OR status = $1)
ORDER BY 
  CASE WHEN $2 = 'created_at_desc' THEN created_at END DESC,
  CASE WHEN $2 = 'created_at_asc' THEN created_at END ASC,
  CASE WHEN $2 = 'project_year_desc' THEN project_year END DESC,
  CASE WHEN $2 = 'project_year_asc' THEN project_year END ASC,
  CASE WHEN $2 = 'project_date_desc' THEN project_date END DESC,
  CASE WHEN $2 = 'project_date_asc' THEN project_date END ASC,
  created_at DESC
LIMIT $4 OFFSET $3
`

type ListProjectsParams struct {
	Status    PageStatus  `json:"status"`
	SortBy    interface{} `json:"sort_by"`
	OffsetVal int32       `json:"offset_val"`
	LimitVal  int32       `json:"limit_val"`
}

func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]Projects, error) {
	rows, err := q.db.Query(ctx, listProjects,
		arg.Status,
		arg.SortBy,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Projects
	for rows.Next() {
		var i Projects
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.Description,
			&i.ProjectDate,
			&i.Status,
			&i.ClientName,
			&i.ProjectYear,
			&i.ProjectUrl,
			&i.Technologies,
			&i.ProjectStatus,
			&i.FeaturedImageID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PublishedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :exec
UPDATE projects
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1
`

func (q *Queries) SoftDeleteProject(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteProject, id)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET 
    title = COALESCE($1, title),
    slug = COALESCE($2, slug),
    description = $3,
    project_date = $4,
    status = COALESCE($5, status),
    client_name = $6,
    project_year = $7,
    project_url = $8,
    technologies = COALESCE($9, technologies),
    project_status = COALESCE($10, project_status),
    featured_image_id = $11,
    published_at = $12,
    updated_at = NOW()
WHERE id = $13
RETURNING id, title, slug, description, project_date, status, client_name, project_year, project_url, technologies, project_status, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type UpdateProjectParams struct {
	Title           string             `json:"title"`
	Slug            string             `json:"slug"`
	Description     pgtype.Text        `json:"description"`
	ProjectDate     pgtype.Date        `json:"project_date"`
	Status          NullPageStatus     `json:"status"`
	ClientName      pgtype.Text        `json:"client_name"`
	ProjectYear     pgtype.Int4        `json:"project_year"`
	ProjectUrl      pgtype.Text        `json:"project_url"`
	Technologies    []byte             `json:"technologies"`
	ProjectStatus   NullProjectStatus  `json:"project_status"`
	FeaturedImageID pgtype.UUID        `json:"featured_image_id"`
	PublishedAt     pgtype.Timestamptz `json:"published_at"`
	ID              uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Projects, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Title,
		arg.Slug,
		arg.Description,
		arg.ProjectDate,
		arg.Status,
		arg.ClientName,
		arg.ProjectYear,
		arg.ProjectUrl,
		arg.Technologies,
		arg.ProjectStatus,
		arg.FeaturedImageID,
		arg.PublishedAt,
		arg.ID,
	)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ProjectDate,
		&i.Status,
		&i.ClientName,
		&i.ProjectYear,
		&i.ProjectUrl,
		&i.Technologies,
		&i.ProjectStatus,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, title, slug, description, project_date, status, client_name, project_year, project_url, technologies, project_status, featured_image_id, created_at, updated_at, published_at, deleted_at
`

type UpdateProjectStatusParams struct {
	Status NullPageStatus `json:"status"`
	ID     uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Projects, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus, arg.Status, arg.ID)
	var i Projects
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.Description,
		&i.ProjectDate,
		&i.Status,
		&i.ClientName,
		&i.ProjectYear,
		&i.ProjectUrl,
		&i.Technologies,
		&i.ProjectStatus,
		&i.FeaturedImageID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PublishedAt,
		&i.DeletedAt,
	)
	return i, err
}
