// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: seo.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSEO = `-- name: CreateSEO :one


INSERT INTO seo (
    entity_type,
    entity_id,
    meta_title,
    meta_description,
    og_title,
    og_description,
    og_image_id,
    canonical_url,
    robots_index,
    robots_follow
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
RETURNING id, entity_type, entity_id, meta_title, meta_description, og_title, og_description, og_image_id, canonical_url, robots_index, robots_follow, created_at, updated_at
`

type CreateSEOParams struct {
	EntityType      string      `json:"entity_type"`
	EntityID        uuid.UUID   `json:"entity_id"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	OgTitle         pgtype.Text `json:"og_title"`
	OgDescription   pgtype.Text `json:"og_description"`
	OgImageID       pgtype.UUID `json:"og_image_id"`
	CanonicalUrl    pgtype.Text `json:"canonical_url"`
	RobotsIndex     pgtype.Bool `json:"robots_index"`
	RobotsFollow    pgtype.Bool `json:"robots_follow"`
}

// backend/sql/queries/seo.sql
// ============================================
// SEO Queries (Polymorphic)
// ============================================
func (q *Queries) CreateSEO(ctx context.Context, arg CreateSEOParams) (Seo, error) {
	row := q.db.QueryRow(ctx, createSEO,
		arg.EntityType,
		arg.EntityID,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgTitle,
		arg.OgDescription,
		arg.OgImageID,
		arg.CanonicalUrl,
		arg.RobotsIndex,
		arg.RobotsFollow,
	)
	var i Seo
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageID,
		&i.CanonicalUrl,
		&i.RobotsIndex,
		&i.RobotsFollow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSEO = `-- name: DeleteSEO :exec
DELETE FROM seo 
WHERE entity_type = $1 AND entity_id = $2
`

type DeleteSEOParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) DeleteSEO(ctx context.Context, arg DeleteSEOParams) error {
	_, err := q.db.Exec(ctx, deleteSEO, arg.EntityType, arg.EntityID)
	return err
}

const getSEO = `-- name: GetSEO :one
SELECT id, entity_type, entity_id, meta_title, meta_description, og_title, og_description, og_image_id, canonical_url, robots_index, robots_follow, created_at, updated_at FROM seo
WHERE entity_type = $1 AND entity_id = $2
`

type GetSEOParams struct {
	EntityType string    `json:"entity_type"`
	EntityID   uuid.UUID `json:"entity_id"`
}

func (q *Queries) GetSEO(ctx context.Context, arg GetSEOParams) (Seo, error) {
	row := q.db.QueryRow(ctx, getSEO, arg.EntityType, arg.EntityID)
	var i Seo
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageID,
		&i.CanonicalUrl,
		&i.RobotsIndex,
		&i.RobotsFollow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSEO = `-- name: UpdateSEO :one
UPDATE seo
SET 
    meta_title = $1,
    meta_description = $2,
    og_title = $3,
    og_description = $4,
    og_image_id = $5,
    canonical_url = $6,
    robots_index = $7,
    robots_follow = $8,
    updated_at = NOW()
WHERE entity_type = $9 AND entity_id = $10
RETURNING id, entity_type, entity_id, meta_title, meta_description, og_title, og_description, og_image_id, canonical_url, robots_index, robots_follow, created_at, updated_at
`

type UpdateSEOParams struct {
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	OgTitle         pgtype.Text `json:"og_title"`
	OgDescription   pgtype.Text `json:"og_description"`
	OgImageID       pgtype.UUID `json:"og_image_id"`
	CanonicalUrl    pgtype.Text `json:"canonical_url"`
	RobotsIndex     pgtype.Bool `json:"robots_index"`
	RobotsFollow    pgtype.Bool `json:"robots_follow"`
	EntityType      string      `json:"entity_type"`
	EntityID        uuid.UUID   `json:"entity_id"`
}

func (q *Queries) UpdateSEO(ctx context.Context, arg UpdateSEOParams) (Seo, error) {
	row := q.db.QueryRow(ctx, updateSEO,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgTitle,
		arg.OgDescription,
		arg.OgImageID,
		arg.CanonicalUrl,
		arg.RobotsIndex,
		arg.RobotsFollow,
		arg.EntityType,
		arg.EntityID,
	)
	var i Seo
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageID,
		&i.CanonicalUrl,
		&i.RobotsIndex,
		&i.RobotsFollow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSEO = `-- name: UpsertSEO :one
INSERT INTO seo (
    entity_type,
    entity_id,
    meta_title,
    meta_description,
    og_title,
    og_description,
    og_image_id,
    canonical_url,
    robots_index,
    robots_follow
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10
)
ON CONFLICT (entity_type, entity_id) 
DO UPDATE SET
    meta_title = EXCLUDED.meta_title,
    meta_description = EXCLUDED.meta_description,
    og_title = EXCLUDED.og_title,
    og_description = EXCLUDED.og_description,
    og_image_id = EXCLUDED.og_image_id,
    canonical_url = EXCLUDED.canonical_url,
    robots_index = EXCLUDED.robots_index,
    robots_follow = EXCLUDED.robots_follow,
    updated_at = NOW()
RETURNING id, entity_type, entity_id, meta_title, meta_description, og_title, og_description, og_image_id, canonical_url, robots_index, robots_follow, created_at, updated_at
`

type UpsertSEOParams struct {
	EntityType      string      `json:"entity_type"`
	EntityID        uuid.UUID   `json:"entity_id"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	OgTitle         pgtype.Text `json:"og_title"`
	OgDescription   pgtype.Text `json:"og_description"`
	OgImageID       pgtype.UUID `json:"og_image_id"`
	CanonicalUrl    pgtype.Text `json:"canonical_url"`
	RobotsIndex     pgtype.Bool `json:"robots_index"`
	RobotsFollow    pgtype.Bool `json:"robots_follow"`
}

func (q *Queries) UpsertSEO(ctx context.Context, arg UpsertSEOParams) (Seo, error) {
	row := q.db.QueryRow(ctx, upsertSEO,
		arg.EntityType,
		arg.EntityID,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgTitle,
		arg.OgDescription,
		arg.OgImageID,
		arg.CanonicalUrl,
		arg.RobotsIndex,
		arg.RobotsFollow,
	)
	var i Seo
	err := row.Scan(
		&i.ID,
		&i.EntityType,
		&i.EntityID,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImageID,
		&i.CanonicalUrl,
		&i.RobotsIndex,
		&i.RobotsFollow,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
